In [1]:
#A python list of lists representing a sudoku puzzle, where 0 represents an empty cell.

sudoku_list = [[0, 0, 4, 3, 0, 0, 2, 0, 9],
 [0, 0, 5, 0, 0, 9, 0, 0, 1],
 [0, 7, 0, 0, 6, 0, 0, 4, 3],
 [0, 0, 6, 0, 0, 2, 0, 8, 7],
 [1, 9, 0, 0, 0, 7, 4, 0, 0],
 [0, 5, 0, 0, 8, 3, 0, 0, 0],
 [6, 0, 0, 0, 0, 0, 1, 0, 5],
 [0, 0, 3, 5, 0, 8, 6, 9, 0],
 [0, 4, 2, 9, 1, 0, 3, 0, 0]]




In [7]:
import numpy as np

# Convert the list of lists to a numpy array called sudoku_array
sudoku_array = np.array(sudoku_list) # Convert the list of lists to a numpy array called sudoku_array
print(sudoku_array) # Print the sudoku_array to check it was created correctly

[[0 0 4 3 0 0 2 0 9]
 [0 0 5 0 0 9 0 0 1]
 [0 7 0 0 6 0 0 4 3]
 [0 0 6 0 0 2 0 8 7]
 [1 9 0 0 0 7 4 0 0]
 [0 5 0 0 8 3 0 0 0]
 [6 0 0 0 0 0 1 0 5]
 [0 0 3 5 0 8 6 9 0]
 [0 4 2 9 1 0 3 0 0]]


In [5]:
print(type(sudoku_array)) # Check the type of sudoku_array

<class 'numpy.ndarray'>


# Creating Arrays from Scratch

In [10]:
zero_array = np.zeros((2,4)) # Create a 2 by 4 array of zeros called zero_array
print(zero_array) # Print zero_array to check it was created correctly


[[0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [12]:
random_array = np.random.rand(3,6) # Create a 3 by 3 array of random numbers between 0 and 1 called random_array
print(random_array) # Print random_array to check it was created correctly

[[0.18896993 0.46411999 0.2468681  0.34702296 0.95991414 0.27313725]
 [0.4391413  0.50454265 0.73182764 0.64463435 0.10591338 0.75971557]
 [0.89296082 0.38156479 0.74174582 0.24851236 0.37719028 0.47706557]]
